name: Deploy to Amazon AWS Beanstalk

on:
  push:
    branches:
#      - develop
      - BE-19-AWS

env:
  EB_PACKAGE_S3_BUCKET_NAME: meduzzen-fastapi
  EB_APPLICATION_NAME: meduzzen-fastapi
  EB_ENVIRONMENT_NAME: Meduzzenfastapi-env
  DEPLOY_PACKAGE_NAME: fastapi_app_${{ github.sha }}.zip
  AWS_REGION_NAME: eu-north-1

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pack into deployment archive
        run: |
          zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy deployment archive to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      - name: Print message for CI finish
        run: echo "CI pipline completed"



  cd_part:
    runs-on: ubuntu-latest
    needs: [ci_part]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create new Elastic Bean app
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "${{ github.sha }}" \
          --description "commit sha: ${{ github.sha }}"

      - name: Deploy new Beanstalk app version
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{env.EB_ENVIRONMENT_NAME}} \
          --version-label "${{ github.sha }}"

      - name: Print message for CD finish
        run: echo "CD pipline completed"
